import pygame
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720


SCREEN = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_CHOICES = [1, 2, 3]
ASTEROID_SPAWN_RATE = 0.5  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 30
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

SHOT_RADIUS = 8
PLAYER_SHOOT_SPEED = 500
SHOOT_COOLDOWN = 0.3
BULLET_RECT_SIZE = (4, 25)


GAME_OVER_TEXT = "Game Over"
PLAY_AGAIN_TEXT = "To play again press: r"
QUIT_TEXT = "To quit press: q"


POWERUPS_RADIUS = 20
POWERUPS_TYPE = ["Faster Shooting", "Piercing", "Shield"]


ENEMY_RADIUS = 25
ENEMY_SPAWN_TIMES = [5, 18, 12, 15, 20, 25]
ENEMY_WAIT_TIME = 3
ENEMY_SHOT_COUNT = [6, 5, 7, 8]

POINT_VALUES = {
    60: 1, 
    40: 2, 
    20: 4, 
    "ufo": 10
}